// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.GeneratorApi.WebApi.Models
{
	/// <summary>
	/// A parse or generate failure.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class FailureDto : ServiceDto<FailureDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public FailureDto()
		{
		}

		public int? Line { get; set; }

		public int? Column { get; set; }

		public string Message { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(FailureDto other)
		{
			return other != null &&
				Line == other.Line &&
				Column == other.Column &&
				Message == other.Message;
		}
	}
}
