// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.GeneratorApi.WebApi.Models
{
	/// <summary>
	/// A named text.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class NamedTextDto : ServiceDto<NamedTextDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public NamedTextDto()
		{
		}

		/// <summary>
		/// The name.
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// The text.
		/// </summary>
		public string Text { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(NamedTextDto other)
		{
			return other != null &&
				Name == other.Name &&
				Text == other.Text;
		}
	}
}
