// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net;
using System.Net.Http;
using Facility.Core;
using Facility.Core.Http;

#pragma warning disable 612 // member is obsolete

namespace Facility.GeneratorApi.Http
{
	/// <summary>
	/// Generates code from Facility Service Definitions.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public static partial class FacilityGeneratorApiHttpMapping
	{
		/// <summary>
		/// Generates code from a service definition.
		/// </summary>
		public static readonly HttpMethodMapping<GenerateRequestDto, GenerateResponseDto> GenerateMapping =
			new HttpMethodMapping<GenerateRequestDto, GenerateResponseDto>.Builder
			{
				HttpMethod = HttpMethod.Post,
				Path = "/generate",
				RequestBodyType = typeof(GenerateRequestDto),
				ResponseMappings =
				{
					new HttpResponseMapping<GenerateResponseDto>.Builder
					{
						StatusCode = (HttpStatusCode) 200,
						ResponseBodyType = typeof(GenerateResponseDto),
					}.Build(),
				},
			}.Build();
	}
}
