// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Threading;
using System.Threading.Tasks;
using Facility.Core;
using Facility.Core.Http;

namespace Facility.GeneratorApi.WebApi.Models.Http
{
	/// <summary>
	/// Generates code from Facility Service Definitions.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class HttpClientFacilityGeneratorApi : HttpClientService, IFacilityGeneratorApi
	{
		/// <summary>
		/// Creates the service.
		/// </summary>
		public HttpClientFacilityGeneratorApi(HttpClientServiceSettings settings = null)
			: base(settings, defaultBaseUri: null)
		{
		}

		/// <summary>
		/// Generates code from a service definition.
		/// </summary>
		public Task<ServiceResult<GenerateResponseDto>> GenerateAsync(GenerateRequestDto request, CancellationToken cancellationToken)
		{
			return TrySendRequestAsync(FacilityGeneratorApiHttpMapping.GenerateMapping, request, cancellationToken);
		}
	}
}
