// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using Facility.Core;

namespace Facility.GeneratorApi
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	internal static class FacilityGeneratorApiMethods
	{
		public static readonly IServiceMethodInfo GetApiInfo =
			ServiceMethodInfo.Create<IFacilityGeneratorApi, GetApiInfoRequestDto, GetApiInfoResponseDto>(
				"getApiInfo", "FacilityGeneratorApi", x => x.GetApiInfoAsync);

		public static readonly IServiceMethodInfo Generate =
			ServiceMethodInfo.Create<IFacilityGeneratorApi, GenerateRequestDto, GenerateResponseDto>(
				"generate", "FacilityGeneratorApi", x => x.GenerateAsync);
	}
}
