// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;

namespace Facility.GeneratorApi
{
	/// <summary>
	/// A parse or generate failure.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class FailureDto : ServiceDto<FailureDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public FailureDto()
		{
		}

		/// <summary>
		/// The line number of the failure.
		/// </summary>
		public int? Line { get; set; }

		/// <summary>
		/// The column number of the failure.
		/// </summary>
		public int? Column { get; set; }

		/// <summary>
		/// The failure message.
		/// </summary>
		public string? Message { get; set; }

		/// <summary>
		/// The JSON serializer.
		/// </summary>
		protected override JsonServiceSerializer JsonSerializer => SystemTextJsonServiceSerializer.Instance;

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(FailureDto? other)
		{
			return other != null &&
				Line == other.Line &&
				Column == other.Column &&
				Message == other.Message;
		}
	}
}
