// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.GeneratorApi
{
	/// <summary>
	/// Request for Generate.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class GenerateRequestDto : ServiceDto<GenerateRequestDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public GenerateRequestDto()
		{
		}

		/// <summary>
		/// The service definition.
		/// </summary>
		public NamedTextDto Definition { get; set; }

		/// <summary>
		/// The generator to use.
		/// </summary>
		public GeneratorDto Generator { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(GenerateRequestDto other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalentDtos(Definition, other.Definition) &&
				ServiceDataUtility.AreEquivalentDtos(Generator, other.Generator);
		}
	}
}
