// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;

namespace Facility.GeneratorApi
{
	/// <summary>
	/// A generator.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class GeneratorDto : ServiceDto<GeneratorDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public GeneratorDto()
		{
		}

		/// <summary>
		/// The name of the generator.
		/// </summary>
		public string? Name { get; set; }

		/// <summary>
		/// Returns the DTO as JSON.
		/// </summary>
		public override string ToString() => SystemTextJsonServiceSerializer.Instance.ToJson(this);

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(GeneratorDto? other)
		{
			return other != null &&
				Name == other.Name;
		}
	}
}
