// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;

namespace Facility.GeneratorApi
{
	/// <summary>
	/// Response for GetApiInfo.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class GetApiInfoResponseDto : ServiceDto<GetApiInfoResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public GetApiInfoResponseDto()
		{
		}

		/// <summary>
		/// The API name.
		/// </summary>
		public string? Api { get; set; }

		/// <summary>
		/// The API version.
		/// </summary>
		public string? Version { get; set; }

		/// <summary>
		/// The JSON serializer.
		/// </summary>
		protected override JsonServiceSerializer JsonSerializer => SystemTextJsonServiceSerializer.Instance;

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(GetApiInfoResponseDto? other)
		{
			return other != null &&
				Api == other.Api &&
				Version == other.Version;
		}
	}
}
