// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.GeneratorApi
{
	/// <summary>
	/// Response for GetApiInfo.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class GetApiInfoResponseDto : ServiceDto<GetApiInfoResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public GetApiInfoResponseDto()
		{
		}

		/// <summary>
		/// The API name.
		/// </summary>
		public string Api { get; set; }

		/// <summary>
		/// The API version.
		/// </summary>
		public string Version { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(GetApiInfoResponseDto other)
		{
			return other != null &&
				Api == other.Api &&
				Version == other.Version;
		}
	}
}
