// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Facility.Core;

namespace Facility.GeneratorApi
{
	/// <summary>
	/// Generates code from Facility Service Definitions.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public partial interface IFacilityGeneratorApi
	{
		/// <summary>
		/// Gets information about the API.
		/// </summary>
		Task<ServiceResult<GetApiInfoResponseDto>> GetApiInfoAsync(GetApiInfoRequestDto request, CancellationToken cancellationToken = default);

		/// <summary>
		/// Generates code from a service definition.
		/// </summary>
		Task<ServiceResult<GenerateResponseDto>> GenerateAsync(GenerateRequestDto request, CancellationToken cancellationToken = default);
	}
}
