// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;

namespace Facility.GeneratorApi
{
	/// <summary>
	/// A named text.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class NamedTextDto : ServiceDto<NamedTextDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public NamedTextDto()
		{
		}

		/// <summary>
		/// The name.
		/// </summary>
		public string? Name { get; set; }

		/// <summary>
		/// The text.
		/// </summary>
		public string? Text { get; set; }

		/// <summary>
		/// The JSON serializer.
		/// </summary>
		protected override JsonServiceSerializer JsonSerializer => SystemTextJsonServiceSerializer.Instance;

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(NamedTextDto? other)
		{
			return other != null &&
				Name == other.Name &&
				Text == other.Text;
		}
	}
}
