// DO NOT EDIT: generated by fsdgenjs

import { IServiceResult } from 'facility-core';

/** Generates code from Facility Service Definitions. */
export interface IFacilityGeneratorApi {
	/** Gets information about the API. */
	getApiInfo(request: IGetApiInfoRequest, context?: unknown): Promise<IServiceResult<IGetApiInfoResponse>>;

	/** Generates code from a service definition. */
	generate(request: IGenerateRequest, context?: unknown): Promise<IServiceResult<IGenerateResponse>>;
}

/** Request for GetApiInfo. */
export interface IGetApiInfoRequest {
}

/** Response for GetApiInfo. */
export interface IGetApiInfoResponse {
	/** The API name. */
	api?: string;

	/** The API version. */
	version?: string;
}

/** Request for Generate. */
export interface IGenerateRequest {
	/** The service definition. */
	definition?: INamedText;

	/** The generator to use. */
	generator?: IGenerator;
}

/** Response for Generate. */
export interface IGenerateResponse {
	/** The output from the generator. */
	output?: INamedText[];

	/** The failure, if any. */
	failure?: IFailure;
}

/** A named text. */
export interface INamedText {
	/** The name. */
	name?: string;

	/** The text. */
	text?: string;
}

/** A generator. */
export interface IGenerator {
	/** The name of the generator. */
	name?: string;
}

/** A parse or generate failure. */
export interface IFailure {
	/** The line number of the failure. */
	line?: number;

	/** The column number of the failure. */
	column?: number;

	/** The failure message. */
	message?: string;
}

